name: HiddenLorax
version: 0.1
api-version: 1.13
description: Automatically plants saplings sitting on grass.
authors: [JosephCW, Dradraen]
website: http://www.github.com/josephcw/PluginHiddenLorax
main: com.github._josephcw.hiddenlorax.HiddenLoraxMain

commands:
  hiddenlorax:
    description: Enable Lorax
    aliases: [lorax, hl]
    usage: /<command>
    permissions: hiddenlorax.settings

permissions:
  hiddenlorax.*:
    default: op
    description: All HiddenLorax permissions
    children:
      hiddenlorax.settings: true
  hiddenlorax.settings:
    description: settings for HiddenLoraxPlugin
